name: Build Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true
      
      - name: Download Minify
        run: wget -qO- https://github.com/tdewolff/minify/releases/download/v2.9.10/minify_linux_amd64.tar.gz | tar xzf -

      - name: Build
        run: |
          hugo --gc --minify --cleanDestinationDir

      - name: Minify Public
        run: ./minify -a -r -o public/ public

      # - name: Create robots.txt
      #   run: |
      #     echo -e 'User-agent: *\nDisallow:\n' > ./public/robots.txt

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public

      # - name: Purge Cloudflare CDN Cache
      #   run: |
      #     curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE }}/purge_cache" \
      #     -H "X-Auth-Email: ${{ secrets.CLOUDFLARE_AUTH_EMAIL }}" \
      #     -H "X-Auth-Key: ${{ secrets.CLOUDFLARE_AUTH_KEY }}" \
      #     -H "Content-Type: application/json" \
      #     --data '{"purge_everything":true}'
